default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DATABASE_HOSTNAME"] %>
  username: x_social_web
  password:  123456789

development:
  <<: *default
  database: x_social_development

test:
  <<: *default
  database: x_social_test

heroku:
  <<: *default
  url: <%= ENV.fetch('JAWSDB_URL', '').sub('mysql://', 'mysql2://') %>

staging:
  <<: *default
  database: x_social_staging

production:
  <<: *default
  #  database: x_social_production
  url: <%= ENV.fetch('JAWSDB_URL', '').sub('mysql://', 'mysql2://') %>
